"""Add additional fields to billing table for Stripe integration

Revision ID: 002_add_stripe_fields_to_billing
Revises: 001_initial_migration
Create Date: 2025-11-20 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '002_add_stripe_fields_to_billing'
down_revision = '001_initial_migration'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('billing', sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('billing', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('billing', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_billing_stripe_customer_id'), 'billing', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_billing_stripe_subscription_id'), 'billing', ['stripe_subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billing_stripe_subscription_id'), table_name='billing')
    op.drop_index(op.f('ix_billing_stripe_customer_id'), table_name='billing')
    op.drop_column('billing', 'updated_at')
    op.drop_column('billing', 'metadata')
    op.drop_column('billing', 'cancel_at_period_end')
    op.drop_column('billing', 'current_period_start')
    # ### end Alembic commands ###